# Generated by Django 5.1.3 on 2024-12-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('product_type', models.CharField(choices=[('Simple', 'Simple'), ('Classified', 'Classified')], max_length=100)),
                ('unit', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Pieces', 'Pieces')], max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='product/images/%Y/%m/%d/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='product/images/%Y/%m/%d/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_provider', models.CharField(blank=True, choices=[('Vimeo', 'Vimeo'), ('Youtube', 'Youtube'), ('Dailymotion', 'Dailymotion')], max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='categories.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
